alter table SHEDULE_SHEDULE add constraint FK_SHEDULE_SHEDULE_ON_STUDENT foreign key (STUDENT_ID) references SHEDULE_STUDENT(ID);
create index IDX_SHEDULE_SHEDULE_ON_STUDENT on SHEDULE_SHEDULE (STUDENT_ID);
